version: "3"

services:
  db:
    container_name: test_db
    image: postgres
    environment:
      POSTGRES_USER : test
      POSTGRES_PASSWORD : 1234
      POSTGRES_DB : test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: test_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL : user@test.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    depends_on:
      - db